import { useCallback, useEffect, useMemo, useRef, useState } from "react"
import { AlertTriangle, ArrowRight, Box, Check, CircleDotDashed, FileBox, FileText, LoaderCircle, RotateCcw, Trash2, UploadCloud } from "lucide-react"
import { Badge, Button, Card, Input, Progress, Select } from "./components/ui"

type Uploads = { step?: File; drawing?: File }
type Feature = { feature_id:string; type:string; subtype:string; dimensions:Record<string,number>; confidence:number; selected:boolean; warnings:string[] }
type Job = { job_id:string; status:string; stage:string; progress:number; error?:string; result?:{geometry?:any;drawing?:any;features:Feature[];warnings:string[]};plans?:any[]; files:any[] }

const API = import.meta.env.BASE_URL.replace(/\/$/, "") + "/api/v1"
const stages:Record<string,string>={queued:"排队等待",starting:"启动解析器",step_geometry:"解析三维几何",pdf_drawing:"识别二维图纸",review:"等待确认",completed:"方案生成完成",failed:"解析失败"}

function fileRole(file:File){const ext=file.name.split(".").pop()?.toLowerCase();return ext==="pdf"?"drawing":"step"}
function formatSize(size:number){return size>1024*1024?`${(size/1024/1024).toFixed(1)} MB`:`${Math.ceil(size/1024)} KB`}

export function App(){
  const [files,setFiles]=useState<Uploads>({}); const [job,setJob]=useState<Job|null>(null); const [error,setError]=useState("");
  const [dragging,setDragging]=useState(false); const [material,setMaterial]=useState("AL-6061-T6"); const [tolerance,setTolerance]=useState("7");
  const [roughness,setRoughness]=useState("1.6"); const inputRef=useRef<HTMLInputElement>(null)
  const [parserOnline,setParserOnline]=useState<boolean|null>(null)
  const busy=job?.status==="queued"||job?.status==="running"
  const addFiles=useCallback((incoming:FileList|File[])=>{setError("");setFiles(prev=>{const next={...prev};for(const f of Array.from(incoming)){const role=fileRole(f);if(!["step","drawing"].includes(role)||f.size>100*1024*1024)continue;next[role as keyof Uploads]=f}return next})},[])
  useEffect(()=>{if(!busy||!job)return;const timer=window.setInterval(async()=>{const r=await fetch(`${API}/parse-jobs/${job.job_id}`);if(r.ok)setJob(await r.json())},1200);return()=>clearInterval(timer)},[busy,job?.job_id])
  useEffect(()=>{fetch(`${API}/health`).then(r=>r.json()).then(data=>setParserOnline(!!data.parser?.available)).catch(()=>setParserOnline(false))},[])
  async function upload(){if(!files.step&&!files.drawing)return;setError("");const body=new FormData();if(files.step)body.append("step_file",files.step);if(files.drawing)body.append("drawing_file",files.drawing);const r=await fetch(`${API}/parse-jobs`,{method:"POST",body});const data=await r.json();if(!r.ok){setError(data.error);return}setJob({...data,progress:0,stage:"queued",files:[]});}
  function updateFeature(id:string,key:"selected"|"diameter_mm"|"depth_mm",value:boolean|number){setJob(current=>{if(!current?.result)return current;return {...current,result:{...current.result,features:current.result.features.map(f=>f.feature_id===id?key==="selected"?{...f,selected:value as boolean}:{...f,dimensions:{...f.dimensions,[key]:value as number}}:f)}}})}
  async function confirm(){if(!job?.result)return;const holes=job.result.features.filter(f=>f.type==="hole"&&f.selected).map(f=>({feature_id:f.feature_id,diameter_mm:f.dimensions.diameter_mm,depth_mm:f.dimensions.depth_mm,hole_type:"through"}));if(!holes.length){setError("请至少选择一个孔特征");return}const r=await fetch(`${API}/parse-jobs/${job.job_id}/confirm`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({holes,material_code:material,tolerance_it:Number(tolerance),roughness_ra:Number(roughness),strategy:"both"})});const data=await r.json();if(!r.ok){setError(data.error);return}setJob(current=>current?{...current,status:"completed",stage:"completed",plans:data.plans}:current)}
  const holes=useMemo(()=>job?.result?.features.filter(f=>f.type==="hole")??[],[job])
  function reset(){setFiles({});setJob(null);setError("")}

  return <main className="min-h-screen bg-[#f7f7f5] text-zinc-950">
    <header className="border-b border-zinc-200 bg-white"><div className="mx-auto flex h-16 max-w-[1440px] items-center justify-between px-5 lg:px-10"><div className="flex min-w-0 items-center gap-3"><div className="grid h-8 w-8 shrink-0 place-items-center bg-zinc-950 text-white"><CircleDotDashed size={18}/></div><div className="min-w-0"><div className="font-semibold tracking-tight">CNCFlow</div><div className="truncate text-[10px] uppercase tracking-[.22em] text-zinc-500">Geometry to Process</div></div></div><Badge className={`shrink-0 gap-1.5 ${parserOnline===false?"border-amber-200 bg-amber-50 text-amber-700":"border-emerald-200 bg-emerald-50 text-emerald-700"}`}><span className={`h-1.5 w-1.5 rounded-full ${parserOnline===false?"bg-amber-500":"bg-emerald-500"}`}/><span className="hidden sm:inline">{parserOnline===false?"解析服务未启动":"解析服务在线"}</span></Badge></div></header>
    <div className="mx-auto max-w-[1440px] px-5 py-8 lg:px-10 lg:py-12">
      <section className="mb-8 grid min-w-0 gap-5 lg:grid-cols-[1fr_auto] lg:items-end"><div className="min-w-0"><div className="mb-3 font-mono text-[10px] uppercase tracking-[.14em] text-zinc-500 sm:text-xs sm:tracking-[.18em]">MVP / Engineering file intake</div><h1 className="max-w-4xl break-words text-[2rem] font-semibold leading-[1.08] tracking-[-.035em] md:text-5xl">上传工程文件，<br className="hidden md:block"/>直接获得可确认的制造特征。</h1></div><p className="max-w-md text-sm leading-6 text-zinc-600">STEP 提供真实几何，PDF 补充材料、公差与技术要求。识别结果确认后生成孔加工工艺、刀具和参数。</p></section>
      {!job&&<Card className="overflow-hidden shadow-[0_24px_70px_rgba(0,0,0,.06)]">
        <div onDragEnter={e=>{e.preventDefault();setDragging(true)}} onDragOver={e=>e.preventDefault()} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);addFiles(e.dataTransfer.files)}} className={`m-3 grid min-h-[360px] min-w-0 place-items-center border border-dashed p-5 text-center transition-all sm:min-h-[390px] sm:p-8 ${dragging?"border-zinc-950 bg-zinc-100":"border-zinc-300 bg-[#fafafa]"}`}>
          <div className="w-full min-w-0 max-w-2xl overflow-hidden"><div className="mx-auto mb-6 grid h-16 w-16 place-items-center rounded-full border border-zinc-200 bg-white shadow-sm"><UploadCloud size={27}/></div><h2 className="mx-auto max-w-full break-all text-xl font-semibold tracking-tight sm:text-2xl">拖拽或上传 STEP / PDF<br className="sm:hidden"/> 工程文件</h2><p className="mt-3 break-words text-sm leading-6 text-zinc-500">推荐同时上传同一零件的三维模型和二维图纸</p><input ref={inputRef} type="file" multiple accept=".step,.stp,.pdf" className="hidden" onChange={e=>e.target.files&&addFiles(e.target.files)}/><Button size="lg" className="mt-7 max-w-full sm:min-w-56" onClick={()=>inputRef.current?.click()}><UploadCloud className="mr-2" size={18}/>选择工程文件</Button><div className="mt-7 flex max-w-full flex-wrap justify-center gap-x-4 gap-y-2 font-mono text-[9px] text-zinc-500 sm:gap-x-8 sm:text-xs"><span>3D · STEP / STP</span><span>2D · PDF</span><span>≤ 100 MB / FILE</span></div></div>
        </div>
        <div className="border-t border-zinc-200 px-6 py-4 text-center text-xs text-zinc-500">文件保存在本地服务器 · 外部视觉识别默认关闭 · 一次最多上传 STEP 与 PDF 各一个</div>
      </Card>}
      {!job&&(files.step||files.drawing)&&<div className="mt-4 grid gap-3 md:grid-cols-2">{Object.entries(files).map(([role,file])=><Card key={role} className="flex items-center gap-4 p-4"><div className="grid h-10 w-10 place-items-center bg-zinc-100">{role==="step"?<FileBox size={20}/>:<FileText size={20}/>}</div><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{file.name}</div><div className="mt-1 font-mono text-[11px] text-zinc-500">{role.toUpperCase()} · {formatSize(file.size)}</div></div><Button variant="ghost" size="sm" onClick={()=>setFiles(p=>({...p,[role]:undefined}))}><Trash2 size={16}/></Button></Card>)}</div>}
      {!job&&(files.step||files.drawing)&&<div className="mt-5 flex justify-end"><Button size="lg" onClick={upload}>开始解析<ArrowRight className="ml-2" size={18}/></Button></div>}
      {job&&<JobView job={job} holes={holes} busy={!!busy} material={material} tolerance={tolerance} roughness={roughness} setMaterial={setMaterial} setTolerance={setTolerance} setRoughness={setRoughness} updateFeature={updateFeature} confirm={confirm} reset={reset}/>}      
      {error&&<div className="mt-5 flex items-start gap-3 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800"><AlertTriangle size={18}/>{error}</div>}
    </div>
  </main>
}

function JobView({job,holes,busy,material,tolerance,roughness,setMaterial,setTolerance,setRoughness,updateFeature,confirm,reset}:any){const g=job.result?.geometry;return <div className="space-y-5">
  {busy&&<Card className="p-7"><div className="mb-6 flex items-center justify-between"><div className="flex items-center gap-3"><LoaderCircle className="animate-spin" size={20}/><div><div className="font-medium">{stages[job.stage]||job.stage}</div><div className="mt-1 font-mono text-xs text-zinc-500">JOB {job.job_id}</div></div></div><div className="font-mono text-sm">{job.progress}%</div></div><Progress value={job.progress}/><div className="mt-4 grid grid-cols-4 gap-2 text-center text-[11px] text-zinc-500">{["上传完成","几何解析","图纸识别","特征确认"].map((s,i)=><div key={s} className={job.progress>=i*30?"text-zinc-950":""}>{s}</div>)}</div></Card>}
  {!busy&&job.result&&<><div className="flex items-center justify-between"><div><div className="font-mono text-xs uppercase tracking-[.18em] text-zinc-500">Parse complete</div><h2 className="mt-2 text-2xl font-semibold">解析结果与特征确认</h2></div><Button variant="outline" onClick={reset}><RotateCcw className="mr-2" size={16}/>重新上传</Button></div>
  <div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="space-y-5"><Card className="p-5"><div className="mb-5 flex items-center gap-2 font-medium"><Box size={18}/>整体几何</div>{g?<div className="grid grid-cols-2 gap-px overflow-hidden border border-zinc-200 bg-zinc-200">{[["包围盒",`${g.bounding_box_mm.x} × ${g.bounding_box_mm.y} × ${g.bounding_box_mm.z} mm`],["实体体积",`${g.volume_cm3} cm³`],["表面积",`${g.surface_area_cm2} cm²`],["拓扑",`${g.face_count} 面 / ${g.edge_count} 边`]].map(([k,v])=><div className="bg-white p-4" key={k}><div className="text-xs text-zinc-500">{k}</div><div className="mt-2 font-mono text-sm">{v}</div></div>)}</div>:<p className="text-sm text-zinc-500">仅上传PDF，无三维几何数据。</p>}</Card><Card className="p-5"><div className="mb-4 font-medium">图纸识别</div>{job.result.drawing?.fields&&Object.keys(job.result.drawing.fields).length?<div className="space-y-3">{Object.entries(job.result.drawing.fields).map(([k,v]:any)=><div key={k} className="flex items-center justify-between border-b border-zinc-100 pb-3 text-sm"><span className="text-zinc-500">{k}</span><span className="font-medium">{Array.isArray(v.value)?v.value.join(", "):String(v.value)}</span></div>)}</div>:<p className="text-sm text-zinc-500">没有识别到图纸字段，或未上传PDF。</p>}</Card></div>
  <Card className="p-5"><div className="mb-1 flex items-center justify-between"><div className="font-medium">孔特征候选</div><Badge>{holes.length} 个圆柱面候选</Badge></div><p className="mb-5 text-xs leading-5 text-zinc-500">圆柱面可能是孔或外圆。请核对直径、深度并取消错误候选。</p><div className="max-h-[430px] space-y-2 overflow-y-auto pr-1">{holes.map((f:Feature)=><div key={f.feature_id} className={`grid grid-cols-[28px_1fr] gap-3 rounded-lg border p-3 ${f.selected?"border-zinc-950":"border-zinc-200 opacity-60"}`}><input type="checkbox" checked={f.selected} onChange={e=>updateFeature(f.feature_id,"selected",e.target.checked)} className="mt-2 h-4 w-4 accent-zinc-950"/><div><div className="mb-3 flex items-center justify-between"><span className="font-mono text-xs">{f.feature_id}</span><Badge>{Math.round(f.confidence*100)}% 推断</Badge></div><div className="grid grid-cols-2 gap-3"><label className="text-xs text-zinc-500">直径 mm<Input type="number" step="0.01" value={f.dimensions.diameter_mm} onChange={e=>updateFeature(f.feature_id,"diameter_mm",Number(e.target.value))} className="mt-1"/></label><label className="text-xs text-zinc-500">深度 mm<Input type="number" step="0.01" value={f.dimensions.depth_mm} onChange={e=>updateFeature(f.feature_id,"depth_mm",Number(e.target.value))} className="mt-1"/></label></div></div></div>)}{!holes.length&&<div className="py-12 text-center text-sm text-zinc-500">未识别到圆柱面候选，可重新上传更完整的STEP。</div>}</div></Card></div>
  <Card className="p-5"><div className="mb-5 font-medium">生成孔加工方案</div><div className="grid gap-4 md:grid-cols-4"><label className="text-xs text-zinc-500">材料<Select value={material} onChange={e=>setMaterial(e.target.value)} className="mt-1"><option value="AL-6061-T6">铝合金 6061-T6</option><option value="SUS-304">304 不锈钢</option><option value="STEEL-45">45号钢</option><option value="TI-6AL4V">钛合金 TC4</option></Select></label><label className="text-xs text-zinc-500">IT等级<Select value={tolerance} onChange={e=>setTolerance(e.target.value)} className="mt-1"><option value="11">IT11 普通</option><option value="8">IT8</option><option value="7">IT7 高精度</option><option value="6">IT6 超精密</option></Select></label><label className="text-xs text-zinc-500">粗糙度 Ra<Input value={roughness} onChange={e=>setRoughness(e.target.value)} type="number" step="0.1" className="mt-1"/></label><div className="flex items-end"><Button className="w-full" onClick={confirm} disabled={!holes.some((h:Feature)=>h.selected)}>确认并生成<ArrowRight className="ml-2" size={16}/></Button></div></div></Card></>}
  {job.plans&&<Card className="p-5"><div className="mb-5 flex items-center gap-2 font-medium"><Check size={18}/>孔加工方案</div><div className="space-y-6">{job.plans.map((p:any)=><div key={p.hole_id}><div className="mb-3 font-mono text-xs text-zinc-500">{p.hole_id} · Ø{p.input.diameter_mm} × {p.input.depth_mm}mm</div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-y border-zinc-200 text-xs text-zinc-500"><th className="py-2">序</th><th>工序</th><th>刀具</th><th>匹配</th><th>稳定参数</th></tr></thead><tbody>{p.plan.tool_chain.map((s:any)=><tr key={s.step} className="border-b border-zinc-100"><td className="py-3 font-mono">{s.step}</td><td>{s.process}</td><td>{s.tool_attrs?.category||"—"}</td><td><Badge>{s.match_tier||s.match_status}</Badge></td><td className="font-mono text-xs">{s.params?.stable?`${s.params.stable.spindle_rpm} rpm · ${s.params.stable.feed_per_rev_mm} mm/rev`:"—"}</td></tr>)}</tbody></table></div></div>)}</div></Card>}
  </div>}
